### ISSUE TITLE
Would you mind removing copyright header from the files?

### ISSUE THREAD

**Issue by vinkaga** [oatpp/example-hls-media-stream#1]
As I understand, this example, like most others, is expected to be copied. 

Would you mind removing the copyright header so that it isn't carried over in other projects?

Also,  if Unlicense (https://choosealicense.com/licenses/unlicense/) were to be chosen, it drops the requirement of carrying copyright header into the derivative work. Note that the dependency, oatpp, will still have all the copyright header requirements.

**Comment by lganzzzo** [comment]
@vinkaga 
Done https://github.com/oatpp/example-hls-media-stream/commit/6ba0c24e00e99b518e1b1ff76f8f09aadda51805.

Thank you for the tip!

Regards,
Leonid
